environment:
  type: poker
  reward_structure: standard

agent:
  type: q_learning  # or 'dqn'
  q_learning:
    learning_rate: 0.1
    discount_factor: 0.95
    exploration_rate: 1.0
    exploration_decay: 0.995
  dqn:
    learning_rate: 0.001
    discount_factor: 0.95
    exploration_rate: 1.0
    exploration_decay: 0.995
    memory_size: 10000
    batch_size: 64
    target_update: 10

training:
  episodes: 1000
  max_steps: 100
  save_path: './models/agent_model.pkl'

logging:
  log_dir: './logs/'
  log_interval: 10
